### ISSUE TITLE
项目安排 | RoadMap

### ISSUE THREAD

**Issue by suyuan32** [suyuan32/simple-admin-core#63]
项目安排

- [x] 登录注册
- [x] 菜单管理
- [x] 角色管理
- [x] 角色权限
- [x] 用户管理
- [x] 操作日志
- [x] 服务注册发现
- [x] 字典功能
- [x] 三方登录管理
- [x] 全面支持 K8s
- [x] 服务监控
- [x] 日志收集
- [x] JWT黑名单
- [x] 定时任务
- [x] 消息队列
- [x] Ent
- [x] 后端 CRUD 代码生成
- [x] 前端 CRUD 代码生成
- [x] 一键运行 demo 脚本
- [x] RPC logic 分组
- [x] Proto 文件拆分 
- [ ] 优化第三方登陆

Road Map

- [x] Login and Register
- [x] Menu Management
- [x] Role Management
- [x] Role Authority
- [x] User Management
- [x] Operation log
- [x] Service discovery
- [x] Dictionary management
- [x] Oauth management
- [x] Fully support K8s
- [x] Service Monitor
- [x] Log collecting
- [x] JWT blacklist
- [x] Job Schedule
- [x] Message queue
- [x] Ent
- [x] Backend CRUD generation
- [x] Frontend CRUD code generation
- [x] docker-compose script
- [x] RPC logic group
- [x] Proto files divide
- [ ] enhance oauth

**Comment by YF-Gooo** [comment]
大佬您好，目前sql里面user只支持单个roleid，有考虑单独分个user-role表进行用户角色管理吗？

**Comment by suyuan32** [comment]
@YF-Gooo 目前是单角色，后续如果要考虑多角色会分表，目前还在优化中，你是需要多角色继承吗？

**Comment by YF-Gooo** [comment]
并非继承，而是多角色的权限叠加。比如一个user既是“测试”，又是“vip用户”。他们的权限会有叠加(取并集)，所以casbin判断的时候可能需要判断多个角色的权限，从而决定是否通过。多角色的前端可以参考这个https://github.com/kuizuo/kz-admin，他也是基于vben写的。笔♥~

**Comment by suyuan32** [comment]
@YF-Gooo  会考虑的，目前项目还在重构迭代中，多种功能都会考虑

**Comment by YF-Gooo** [comment]
> 
嗯嗯嗯，这个项目给了我很多参考，万分感谢

**Comment by suyuan32** [comment]
@YF-Gooo 新版本已支持多角色

**Comment by renleihuman** [comment]
建议增加excel导出、导入功能

**Comment by suyuan32** [comment]
> 建议增加excel导出、导入功能

@renleihuman 导出功能vben已经有了的，需要使用vxeTable组件，导入功能得自己实现
https://vben.vvbin.cn/#/comp/table/vxeTable

**Comment by suyuan32** [comment]
一般导入是在sql客户端直接导入就行，例如navicat或者vscode都有导入功能

**Comment by tomasky** [comment]
点击 “添加” 按钮，好像有一点点延迟。非常不错的项目，要是能继续简化开发流程，就更好了。

**Comment by tomasky** [comment]
请问一下，数据库支持自动分表分库吗？

**Comment by suyuan32** [comment]
> 请问一下，数据库支持自动分表分库吗？

暂不支持，可以去 ent 问问，不过手动是支持的

**Comment by Robtzz** [comment]
> 一般导入是在sql客户端直接导入就行，例如navicat或者vscode都有导入功能

啊？在数据库操作那还说啥
